error: 
    status - 500 
    message - Error: Already Exist EmailId
    at _callee$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:7:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:09:33.281Z"}
error: 
    status - 500 
    message - TypeError: UserService.login is not a function
    at _callee2$ (D:\NodeJS\FundoNotes\src\controllers\/user.controller.js:32:36)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\NodeJS\FundoNotes\src\controllers\/user.controller.js:30:20)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\NodeJS\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\NodeJS\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\NodeJS\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\NodeJS\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\NodeJS\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\NodeJS\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:44:57.878Z"}
error: 
    status - 500 
    message - Error: Enter Valid EmailId
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:46:04.295Z"}
error: 
    status - 500 
    message - Error: Enter Valid EmailId
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:46:48.710Z"}
error: 
    status - 500 
    message - Error: Enter valid Password
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:22:13)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:48:29.751Z"}
error: 
    status - 500 
    message - Error: Enter Valid EmailId
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:25:11)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-23T16:48:49.911Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 8 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T02:46:35.860Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be less than or equal to 15 characters long 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T02:47:34.058Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:11:44.016Z"}
error: 
    status - 500 
    message - ValidationError: "email" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:12:00.140Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:12:10.587Z"}
error: 
    status - 500 
    message - ValidationError: "password" is required 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T03:12:28.692Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:26:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:10:58.802Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:26:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:18:11.929Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:27:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:20:25.862Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:27:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:21:32.193Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:208:17)
    at D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (D:\NodeJS\FundoNotes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (D:\NodeJS\FundoNotes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (D:\NodeJS\FundoNotes\src\services\/user.service.js:27:33)
    at tryCatch (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\NodeJS\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-24T14:24:12.511Z"}
